version: '3'

services:

  apache:
    image: apache
    deploy:
      replicas: 3
    ports:
      - "8080:80"

  node:
    image: serverjs
    deploy:
      replicas: 3
    ports:
      - "8090:8090"

  mysql:
    image: mysql
    deploy:
      replicas: 1
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: prueba
